categories = {
    "school": [
       "./resources/schools/dolnoslaskie.csv",
       "./resources/schools/kujawsko-pomorskie.csv",
       "./resources/schools/lodzkie.csv",
       "./resources/schools/lubelskie.csv",
       "./resources/schools/lubuskie.csv",
       "./resources/schools/malopolskie.csv",
       "./resources/schools/mazowieckie.csv",
       "./resources/schools/opolskie.csv",
       "./resources/schools/podkarpackie.csv",
       "./resources/schools/podlaskie.csv",
       "./resources/schools/pomorskie.csv",
       "./resources/schools/slaskie.csv",
       "./resources/schools/swietokrzyskie.csv",
       "./resources/schools/warminsko-mazurskie.csv",
       "./resources/schools/wielkopolskie.csv",
       "./resources/schools/zachodniopomorskie.csv",
       "./resources/schools/zagranica.csv",
    ],
    "statue": [
       "./resources/statues/dolnoslaskie.csv",
       "./resources/statues/kujawsko-pomorskie.csv",
       "./resources/statues/lodzkie.csv",
       "./resources/statues/lubelskie.csv",
       "./resources/statues/lubuskie.csv",
       "./resources/statues/malopolskie.csv",
       "./resources/statues/mazowieckie.csv",
       "./resources/statues/opolskie.csv",
       "./resources/statues/podkarpackie.csv",
       "./resources/statues/podlaskie.csv",
       "./resources/statues/pomorskie.csv",
       "./resources/statues/slaskie.csv",
       "./resources/statues/swietokrzyskie.csv",
       "./resources/statues/warminsko-mazurskie.csv",
       "./resources/statues/wielkopolskie.csv",
       "./resources/statues/zachodniopomorskie.csv",
       "./resources/statues/zagranica.csv",
    ],
    "street": [
       "./resources/streets/dolnoslaskie.csv",
       "./resources/streets/kujawsko-pomorskie.csv",
       "./resources/streets/lodzkie.csv",
       "./resources/streets/lubelskie.csv",
       "./resources/streets/lubuskie.csv",
       "./resources/streets/malopolskie.csv",
       "./resources/streets/mazowieckie.csv",
       "./resources/streets/opolskie.csv",
       "./resources/streets/podkarpackie.csv",
       "./resources/streets/podlaskie.csv",
       "./resources/streets/pomorskie.csv",
       "./resources/streets/slaskie.csv",
       "./resources/streets/swietokrzyskie.csv",
       "./resources/streets/warminsko-mazurskie.csv",
       "./resources/streets/wielkopolskie.csv",
       "./resources/streets/zachodniopomorskie.csv",
       "./resources/streets/zagranica.csv",
    ],
    "church": [
       "./resources/churches.csv",
    ],
    "other": [
       "./resources/airports.csv",
       "./resources/hospitals.csv",
       "./resources/others.csv",
    ],
}